# Generated by Django 5.0.6 on 2024-05-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_code', models.CharField(max_length=100, verbose_name='Код')),
                ('building_name', models.CharField(max_length=100, verbose_name='Здание')),
                ('block', models.CharField(max_length=10, verbose_name='Корпус/Блок')),
                ('section', models.IntegerField(verbose_name='Секция')),
                ('entrance', models.IntegerField(verbose_name='Подъезд')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('room_number', models.CharField(max_length=10, verbose_name='№ помещения (по экспликации)')),
                ('room_name', models.CharField(max_length=255, verbose_name='Наименование помещения')),
                ('finishing_type', models.CharField(max_length=50, verbose_name='Тип отделки')),
                ('construction', models.CharField(max_length=50, verbose_name='Конструктив')),
                ('layer', models.CharField(max_length=50, verbose_name='Слой')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('unit', models.CharField(max_length=20, verbose_name='Ед.об.')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объём (Всего)')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
            ],
        ),
    ]
