# Generated by Django 5.0.6 on 2024-12-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeilingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rough_finish', models.CharField(max_length=255, verbose_name='Черновая отделка')),
                ('clean_finish', models.CharField(max_length=255, verbose_name='Чистовая отделка')),
            ],
            options={
                'verbose_name': 'Тип отделки потолка',
                'verbose_name_plural': 'Типы отделки потолков',
            },
        ),
        migrations.CreateModel(
            name='FloorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rough_finish', models.CharField(max_length=255, verbose_name='Черновая отделка')),
                ('clean_finish', models.CharField(max_length=255, verbose_name='Чистовая отделка')),
            ],
            options={
                'verbose_name': 'Тип отделки пола',
                'verbose_name_plural': 'Типы отделки полов',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Код')),
                ('block', models.CharField(max_length=10, verbose_name='Здание')),
                ('floor', models.IntegerField(blank=True, verbose_name='Этаж')),
                ('room_number', models.CharField(blank=True, max_length=50, verbose_name='Номер помещения')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('area', models.FloatField(default=0, verbose_name='Площадь')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='WallType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('rough_finish', models.CharField(max_length=255, verbose_name='Черновая отделка')),
                ('clean_finish', models.CharField(max_length=255, verbose_name='Чистовая отделка')),
            ],
            options={
                'verbose_name': 'Тип отделки стен',
                'verbose_name_plural': 'Типы отделки стен',
            },
        ),
        migrations.CreateModel(
            name='FloorWorkVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_number', models.IntegerField(verbose_name='Номер элемента')),
                ('volume', models.FloatField(default=0, verbose_name='Объем (м²)')),
                ('completion_percentage', models.FloatField(default=0, verbose_name='Процент выполнения')),
                ('unit', models.CharField(default='м²', max_length=10, verbose_name='Ед. изм.')),
                ('floor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.floortype')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_volumes', to='main.room')),
            ],
            options={
                'verbose_name': 'Объем отделки пола',
                'verbose_name_plural': 'Объемы отделки полов',
            },
        ),
        migrations.CreateModel(
            name='CeilingWorkVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_number', models.IntegerField(verbose_name='Номер элемента')),
                ('volume', models.FloatField(default=0, verbose_name='Объем (м²)')),
                ('completion_percentage', models.FloatField(default=0, verbose_name='Процент выполнения')),
                ('unit', models.CharField(default='м²', max_length=10, verbose_name='Ед. изм.')),
                ('ceiling_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ceilingtype')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_volumes', to='main.room')),
            ],
            options={
                'verbose_name': 'Объем отделки потолков',
                'verbose_name_plural': 'Объемы отделки потолков',
            },
        ),
        migrations.CreateModel(
            name='WallWorkVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_number', models.IntegerField(verbose_name='Номер элемента')),
                ('volume', models.FloatField(default=0, verbose_name='Объем (м²)')),
                ('completion_percentage', models.FloatField(default=0, verbose_name='Процент выполнения')),
                ('unit', models.CharField(default='м²', max_length=10, verbose_name='Ед. изм.')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_volumes', to='main.room')),
                ('wall_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.walltype')),
            ],
            options={
                'verbose_name': 'Объем отделки стен',
                'verbose_name_plural': 'Объемы отделки стен',
            },
        ),
    ]
