# Generated by Django 5.0.6 on 2025-01-09 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceilingworkvolume',
            name='element_number',
        ),
        migrations.RemoveField(
            model_name='floorworkvolume',
            name='element_number',
        ),
        migrations.RemoveField(
            model_name='wallworkvolume',
            name='element_number',
        ),
        migrations.AlterField(
            model_name='ceilingworkvolume',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceilingworkvolume_volumes', to='main.room'),
        ),
        migrations.AlterField(
            model_name='floorworkvolume',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorworkvolume_volumes', to='main.room'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='wallworkvolume',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallworkvolume_volumes', to='main.room'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Проект'),
        ),
    ]
