# Generated by Django 5.0.6 on 2025-01-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_ceilingworkvolume_element_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='area',
        ),
        migrations.AddField(
            model_name='room',
            name='area_ceiling',
            field=models.FloatField(default=0, verbose_name='Площадь потолка'),
        ),
        migrations.AddField(
            model_name='room',
            name='area_floor',
            field=models.FloatField(default=0, verbose_name='Площадь пола'),
        ),
        migrations.AddField(
            model_name='room',
            name='area_wall',
            field=models.FloatField(default=0, verbose_name='Площадь стен'),
        ),
    ]
