# Generated by Django 5.0.6 on 2024-12-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_organization_name_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceilingworkvolume',
            name='element_number',
        ),
        migrations.RemoveField(
            model_name='floorworkvolume',
            name='element_number',
        ),
        migrations.RemoveField(
            model_name='wallworkvolume',
            name='element_number',
        ),
    ]
